// Swim workout library — the swim analogue of the endurance (ride/run) catalog. Distance-based sets on a send-off,
// prescribed relative to CSS (see docs/swimming-coaching.md). Grounded in Schneider's Swimmer's Workout Handbook
// structure (warm-up → drills → main → cool-down), Total Immersion technique, and CSS threshold sets. The library is
// GENERATED by `scripts/build-swim-workouts.mjs` → `generated/swim-workouts.json` (115 workouts across 7 focuses;
// re-run the script to regenerate). Distances in metres (a yard pool reads the same numbers). `tss` is a nominal sTSS
// for a ~1:40/100 CSS swimmer and scales with the athlete's real CSS at runtime.
import swimData from './generated/swim-workouts.json'

export type SwimLevel = 'beginner' | 'intermediate' | 'advanced'
export type SwimFocus = 'technique' | 'endurance' | 'threshold' | 'speed' | 'mixed' | 'recovery' | 'openwater'

export interface SwimWorkout {
  id: string
  name: string
  level: SwimLevel
  focus: SwimFocus
  distanceM: number
  durationMin: number
  tss: number
  summary: string // one-liner
  structure: { part: string; detail: string }[] // warm-up / drills / main / cool-down
}

export const swimWorkouts = swimData as unknown as SwimWorkout[]

export const swimFocusLabel: Record<SwimFocus, string> = { technique: 'Technique', endurance: 'Endurance', threshold: 'Threshold (CSS)', speed: 'Speed', mixed: 'Mixed', recovery: 'Recovery', openwater: 'Open water' }
